version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python -m pytest --junitxml target/reports/junit.xml src/test/python/app

reports:
  junit:
    files:
      - '**/*'
    base-directory:
      - 'target/reports/junit.xml'